name: 'build'

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch:

env:
  CI: true
  DOCKER_BUILDKIT: 1

jobs:

  multi:
    strategy:
      fail-fast: false
      matrix:
        file: [ sphinx, miktex, texlive, hugo, bookdown, doxygen ]
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build
      run: ./build.sh "${{ matrix.file }}.dockerfile"

    - name: Push
      if: github.event_name != 'pull_request'
      run: |
        echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
        set +e
        for img in `echo $(docker images btdi/* | awk -F ' ' '{print $1 ":" $2}') | cut -d ' ' -f2-`; do
          docker push "$img"
        done
        docker logout
